#!/bin/bash

# Script de teste para validar as correções de duplicação de refeições

echo "=========================================="
echo "TESTE: Correção de Duplicação de Refeições"
echo "=========================================="
echo ""

# Verificar se o servidor está rodando
echo "1. Verificando servidor..."
if curl -s http://localhost:8000/health > /dev/null 2>&1; then
    echo "   ✅ Servidor está rodando em http://localhost:8000"
else
    echo "   ❌ Servidor não está respondendo"
    echo "   Execute: ./scripts/start_server.sh"
    exit 1
fi

echo ""
echo "2. Instruções de teste manual:"
echo ""
echo "   A. GERAR NOVO PLANO:"
echo "      1. Acesse http://localhost:8000/home.html"
echo "      2. Faça login"
echo "      3. Vá para aba 'Profile'"
echo "      4. Preencha todos os dados obrigatórios"
echo "      5. Clique em 'Gerar novo plano'"
echo "      6. Aguarde a geração (pode levar 1-2 minutos)"
echo ""
echo "   B. VERIFICAR ABA DAILY PLAN:"
echo "      1. Timeline deve mostrar para cada dia:"
echo "         ✅ Horários em formato brasileiro (07h30, 12h00, 19h00)"
echo "         ✅ Checks de glicemia em português:"
echo "            - 'Glicemia em Jejum'"
echo "            - 'Glicemia Pré-Prandial'"
echo "         ✅ Refeições com descrições (não 'Veja detalhes na aba Nutrição')"
echo "         ✅ Atividades em português:"
echo "            - 'Caminhada Leve'"
echo "            - 'Caminhada Moderada'"
echo "            - 'Alongamento Leve'"
echo "         ❌ NÃO deve ter eventos com 'Breakfast', 'Lunch', 'Dinner'"
echo "         ❌ NÃO deve ter horários em formato AM/PM"
echo ""
echo "   C. VERIFICAR ABA NUTRITION:"
echo "      1. Deve mostrar aproximadamente 35 refeições"
echo "      2. Cada refeição deve ter:"
echo "         ✅ Dia da semana (SEGUNDA-FEIRA, TERÇA-FEIRA, etc.)"
echo "         ✅ Tipo (Café da manhã, Almoço, Jantar)"
echo "         ✅ Nome da refeição"
echo "         ✅ Descrição detalhada"
echo "         ✅ Informação nutricional completa"
echo "      3. Verificações:"
echo "         ❌ NÃO deve haver refeições duplicadas"
echo "         ❌ NÃO deve haver refeições sem detalhes"
echo "         ✅ Total de refeições: 21 (3 por dia × 7 dias) ou 35 (5 por dia × 7 dias)"
echo ""
echo "   D. VERIFICAR CONSOLE DO NAVEGADOR (F12):"
echo "      Deve aparecer:"
echo "      📊 Carregadas X refeições detalhadas do array meals"
echo ""
echo "   E. VERIFICAR RESPONSE DA API:"
echo "      1. Abra DevTools (F12) → Network"
echo "      2. Recarregue a página"
echo "      3. Encontre request para /api/users/{id}/plan"
echo "      4. Verificar JSON de resposta:"
echo "         ✅ plan_json.meals deve ter ~35 refeições detalhadas"
echo "         ✅ plan_json.timeline deve ter ~63 eventos (21 glicemia + 21 refeições + 21 atividades)"
echo "         ✅ Cada evento de refeição na timeline deve ter campo 'meal_ref'"
echo "         ✅ meal_ref deve estar no formato 'DIA-TIPO' (ex: 'SEGUNDA-FEIRA-Café da manhã')"
echo "         ✅ time_display deve estar em formato brasileiro (ex: '07h30')"
echo "         ✅ Descrições em português (sem 'AM', 'PM', 'Breakfast', etc.)"
echo ""

echo "=========================================="
echo "MUDANÇAS IMPLEMENTADAS"
echo "=========================================="
echo ""
echo "✅ Prompt traduzido para português"
echo "✅ Formato de hora mudado para brasileiro (24h)"
echo "✅ Timeline agora REFERENCIA meals via meal_ref"
echo "✅ Timeline não gera mais refeições duplicadas"
echo "✅ Aba Nutrition usa APENAS array meals"
echo "✅ Aba Daily Plan enriquece timeline com dados de meals"
echo "✅ Checks de glicemia em português"
echo "✅ Atividades em português"
echo ""

echo "=========================================="
echo "ARQUIVOS MODIFICADOS"
echo "=========================================="
echo ""
echo "1. backend/meal_plan_rag.py"
echo "   - Task 8 (plan_json_task) reescrita"
echo "   - Linhas ~437-570"
echo ""
echo "2. frontend/home.html"
echo "   - loadNutritionPlan() simplificada"
echo "   - loadExistingPlan() com enriquecimento"
echo "   - loadPlan() com enriquecimento"
echo ""

echo "=========================================="
echo "TESTE AUTOMÁTICO (Opcional)"
echo "=========================================="
echo ""
echo "Para teste automático via API:"
echo ""
echo "# 1. Obter user_id"
echo "USER_ID=1  # Substitua pelo seu ID"
echo ""
echo "# 2. Gerar novo plano"
echo "curl -X POST http://localhost:8000/api/meal-plan/generate \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"user_id\": '\$USER_ID'}' \\"
echo "  -o plan_response.json"
echo ""
echo "# 3. Verificar o JSON gerado"
echo "echo 'Verificando meals array...'"
echo "jq '.plan_json.meals | length' plan_response.json"
echo ""
echo "echo 'Verificando timeline array...'"
echo "jq '.plan_json.timeline | length' plan_response.json"
echo ""
echo "echo 'Verificando meal_ref na timeline...'"
echo "jq '.plan_json.timeline[] | select(.event_type == \"Meal\") | .meal_ref' plan_response.json | head -5"
echo ""
echo "echo 'Verificando formato de hora...'"
echo "jq '.plan_json.timeline[] | .time_display' plan_response.json | head -10"
echo ""

echo "=========================================="
echo "Para mais informações, consulte:"
echo "  CORRECAO_DUPLICACAO_REFEICOES.md"
echo "=========================================="
